#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
replace_image.py — find and replace any photo on the Athienitis website.

Every photo on the site is a named *slot* (see images.json, generated by the build).
This tool lets you see what each slot is, where it appears, and swap it for a new
image — either a URL or a local file you drop in. Run it from the repo root.

  python tools/replace_image.py list                 # all slots, grouped, with where they're used
  python tools/replace_image.py list bakery          # filter by text (slot, description or file)
  python tools/replace_image.py show shop_bakery     # details + current URL + opens a preview page
  python tools/replace_image.py preview              # writes tools/preview.html — a contact sheet of every image
  python tools/replace_image.py set shop_bakery https://example.com/my-photo.jpg
  python tools/replace_image.py set shop_bakery ~/Desktop/bakery.jpg     # copies to assets/img/shop_bakery.jpg
  python tools/replace_image.py set product_bk1 ./bread.jpg --no-resize  # keep original dimensions
  python tools/replace_image.py undo shop_bakery     # restore the original hosted photo

Notes
- Replacing updates every HTML file and js/catalog.js that uses that slot, with the
  correct relative path for each file (../ for pages in shops/ and blog/).
- Local files are resized to the slot's size (needs Pillow: pip install pillow);
  without Pillow the file is copied as-is.
- Hosted URLs are used verbatim. Prefer https and a sensible width (≥ 900px for heroes).
"""
import sys, os, json, re, shutil, webbrowser, html

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
MANIFEST = os.path.join(ROOT, "images.json")
ASSETS = os.path.join(ROOT, "assets", "img")
STATE = os.path.join(ROOT, "tools", "replacements.json")

def load():
    with open(MANIFEST, encoding="utf-8") as f: return json.load(f)
def load_state():
    return json.load(open(STATE, encoding="utf-8")) if os.path.exists(STATE) else {}
def save_state(s):
    os.makedirs(os.path.dirname(STATE), exist_ok=True)
    json.dump(s, open(STATE, "w", encoding="utf-8"), indent=1, ensure_ascii=False)

def current_src(slot, m, state):
    return state.get(slot, {}).get("current", m["url"])

def group(slot):
    for g in ("product_", "shop_", "hero_", "gallery_", "tile_", "how_", "manifesto_", "blog_", "recipe_", "bundle_", "app_", "business_", "account_", "demo_", "login", "register", "contact", "offers", "faq", "departments", "home_"):
        if slot.startswith(g): return g.rstrip("_")
    return "other"

def cmd_list(q=None):
    m = load(); state = load_state()
    rows = [r for r in m if not q or q.lower() in (r["slot"] + " " + r["description"] + " " + " ".join(r["files"])).lower()]
    rows.sort(key=lambda r: (group(r["slot"]), r["slot"]))
    last = None
    for r in rows:
        g = group(r["slot"])
        if g != last: print(f"\n== {g.upper()} =="); last = g
        flag = "  (replaced)" if r["slot"] in state else ""
        print(f"  {r['slot']:<26} {r['size']:>9}  {r['description']}{flag}")
        print(f"  {'':<26} {'':>9}  used in: {', '.join(r['files'])}")
    print(f"\n{len(rows)} image slot(s). `show <slot>` for details, `set <slot> <url|file>` to replace.")

def find(slot):
    for r in load():
        if r["slot"] == slot: return r
    sys.exit(f"No slot named '{slot}'. Try: python tools/replace_image.py list {slot.split('_')[0]}")

def cmd_show(slot):
    r = find(slot); state = load_state()
    print(f"slot:        {r['slot']}\ndescription: {r['description']}\nsize:        {r['size']}\noriginal:    {r['url']}\ncurrent:     {current_src(slot, r, state)}\nused in:")
    for f in r["files"]: print(f"  - {f}")
    p = write_preview([r]); print(f"preview:     {p}")
    try: webbrowser.open("file://" + p)
    except Exception: pass

def write_preview(rows):
    state = load_state()
    cards = "".join(
        f'<figure><img src="{html.escape(abs_src(current_src(r["slot"], r, state)))}" loading="lazy"><figcaption><b>{r["slot"]}</b><br>{html.escape(r["description"])}<br><small>{r["size"]} · {", ".join(r["files"])}</small></figcaption></figure>'
        for r in rows)
    out = os.path.join(ROOT, "tools", "preview.html")
    os.makedirs(os.path.dirname(out), exist_ok=True)
    open(out, "w", encoding="utf-8").write(f"""<!doctype html><meta charset="utf-8"><title>Athienitis — image slots</title>
<style>body{{font:14px/1.5 system-ui;margin:24px;background:#f6f7f3}}h1{{font-size:20px}}.g{{display:grid;grid-template-columns:repeat(auto-fill,minmax(240px,1fr));gap:16px}}figure{{margin:0;background:#fff;border-radius:12px;overflow:hidden;box-shadow:0 2px 10px rgba(0,0,0,.06)}}img{{width:100%;aspect-ratio:4/3;object-fit:cover;display:block;background:#ddd}}figcaption{{padding:10px 12px}}small{{color:#666}}</style>
<h1>Athienitis image slots ({len(rows)})</h1><p>Replace any of these with <code>python tools/replace_image.py set &lt;slot&gt; &lt;url or file&gt;</code></p><div class="g">{cards}</div>""")
    return out

def abs_src(src):
    return src if src.startswith("http") else "file://" + os.path.join(ROOT, src)

def cmd_preview():
    p = write_preview(sorted(load(), key=lambda r: (group(r["slot"]), r["slot"])))
    print("Wrote", p)
    try: webbrowser.open("file://" + p)
    except Exception: pass

def rel_for(file_rel, target_rel):
    depth = file_rel.count("/")
    return ("../" * depth) + target_rel

def replace_in_files(r, old_id, new_src_rel_or_url):
    """Rewrite every occurrence of the slot's image in its files."""
    pat = re.compile(r'https://images\.unsplash\.com/photo-' + re.escape(old_id) + r'[^"\'\s)]*slot=' + re.escape(r["slot"]) + r'(?=["\'\s)])')
    changed = 0
    for f in r["files"]:
        path = os.path.join(ROOT, f)
        txt = open(path, encoding="utf-8").read()
        new = new_src_rel_or_url if new_src_rel_or_url.startswith("http") else rel_for(f, new_src_rel_or_url)
        # also catch an earlier local replacement
        txt2 = pat.sub(new, txt)
        prev = load_state().get(r["slot"], {}).get("current")
        if prev and not prev.startswith("http"):
            txt2 = txt2.replace(rel_for(f, prev), new)
        elif prev and prev.startswith("http"):
            txt2 = txt2.replace(prev, new)
        if txt2 != txt:
            open(path, "w", encoding="utf-8").write(txt2); changed += 1
    return changed

def cmd_set(slot, source, resize=True):
    r = find(slot); state = load_state()
    w, h = map(int, r["size"].split("x"))
    if source.startswith("http"):
        new = source
    else:
        src = os.path.expanduser(source)
        if not os.path.exists(src): sys.exit(f"File not found: {src}")
        os.makedirs(ASSETS, exist_ok=True)
        ext = os.path.splitext(src)[1].lower() or ".jpg"
        if ext not in (".jpg", ".jpeg", ".png", ".webp"): sys.exit("Use a .jpg, .png or .webp file")
        dest = os.path.join(ASSETS, f"{slot}{'.jpg' if ext in ('.jpeg',) else ext}")
        done = False
        if resize:
            try:
                from PIL import Image, ImageOps
                im = Image.open(src); im = ImageOps.exif_transpose(im)
                im = ImageOps.fit(im, (w, h), method=Image.LANCZOS)
                if dest.lower().endswith((".jpg", ".jpeg")): im = im.convert("RGB"); im.save(dest, quality=84, optimize=True)
                else: im.save(dest, optimize=True)
                done = True; print(f"Resized to {w}x{h} → {os.path.relpath(dest, ROOT)}")
            except ImportError:
                print("Pillow not installed — copying without resizing (pip install pillow to enable).")
        if not done: shutil.copy2(src, dest); print(f"Copied → {os.path.relpath(dest, ROOT)}")
        new = os.path.relpath(dest, ROOT).replace(os.sep, "/")
    n = replace_in_files(r, r["photo_id"], new)
    state[slot] = {"current": new, "original": r["url"]}; save_state(state)
    print(f"Updated {n} file(s) for slot '{slot}':")
    for f in r["files"]: print(f"  - {f}")
    print("Commit the changed files (and assets/img/ if a local file was used).")

def cmd_undo(slot):
    r = find(slot); state = load_state()
    if slot not in state: sys.exit("Nothing to undo for this slot.")
    n = replace_in_files(r, r["photo_id"], r["url"])
    del state[slot]; save_state(state)
    print(f"Restored original photo in {n} file(s).")

if __name__ == "__main__":
    a = sys.argv[1:]
    if not a or a[0] in ("-h", "--help", "help"): print(__doc__); sys.exit(0)
    cmd = a[0]
    if cmd == "list": cmd_list(a[1] if len(a) > 1 else None)
    elif cmd == "show" and len(a) > 1: cmd_show(a[1])
    elif cmd == "preview": cmd_preview()
    elif cmd == "set" and len(a) > 2: cmd_set(a[1], a[2], resize="--no-resize" not in a)
    elif cmd == "undo" and len(a) > 1: cmd_undo(a[1])
    else: print(__doc__)
